openapi: 3.0.0
info:
  title: EUsage Reports
  version: v1
paths:
  /eusage-reports/report-titles:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
    get:
      description: Get titles with links to KB
      operationId: getReportTitles
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: schemas/reportTitles.json
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
  /eusage-reports/report-titles/from-counter:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
    post:
      description: Parse counter reports
      operationId: postFromCounter
      requestBody:
        content:
          application/json:
            schema:
              $ref: schemas/fromCounterRequest.json
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: schemas/reportTitles.json
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
  /eusage-reports/title-data:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
    get:
      description: Get title data
      operationId: getTitleData
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: schemas/reportTitleData.json
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
components:
  responses:
    trait_400:
      description: Bad request
      content:
        text/plain:
          schema:
            type: string
            example: Invalid JSON in request
        application/json:
          schema:
            type: object
            example: {"error":"Invalid JSON in request"}
    trait_500:
      description: Internal error
      content:
        text/plain:
          schema:
            type: string
            example: Internal server error, contact administrator
  schemas:
    errors:
      $ref: schemas/errors.json
