openapi: 3.0.0
info:
  title: Use Over Time
  version: v1.0
paths:
  /eusage-reports/stored-reports/use-over-time:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
      - in: query
        name: agreementId
        required: true
        description: UUID of the agreement we generate the report for
        schema:
          type: string
      - in: query
        name: startDate
        required: true
        description: starting date of use in yyyy-mm-dd format, for example 2020-10-01
        schema:
          type: string
          format: date
          example: "2020-10-01"
      - in: query
        name: endDate
        required: true
        description: end date (exclusive) of use in yyyy-mm-dd format, for example endDate=2020-11-01 ends at 2020-10-31T23:59:59.999...
        schema:
          type: string
          format: date
          example: "2020-11-01"
    get:
      description: Use over time report for one aggreement 
      operationId: useOverTime
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: schemas/reportUseOverTime.json
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
components:
  responses:
    trait_400:
      description: Bad request
      content:
        text/plain:
          schema:
            type: string
            example: Invalid JSON in request
        application/json:
          schema:
            type: object
            example: {"error":"Invalid JSON in request"}
    trait_404:
      description: Not Found
      content:
        text/plain:
          schema:
            type: string
            example: Identifier 596d9f60-cda3-44d2-a4a1-2f48b7d4d23c not found
        application/json:
          schema:
            type: object
            example: {"error":"Identifier 596d9f60-cda3-44d2-a4a1-2f48b7d4d23c not found"}
    trait_500:
      description: Internal error
      content:
        text/plain:
          schema:
            type: string
            example: Internal server error, contact administrator
  schemas:
    errors:
      $ref: schemas/errors.json
      